---
repos:
 - repo: https://github.com/sphinx-contrib/sphinx-lint
   rev: "v0.9.1"
   hooks:
    - id: sphinx-lint
 - repo: https://github.com/PyCQA/doc8
   rev: v1.1.1
   hooks:
    - id: doc8
      files: ^docs/.*\.rst$
 - repo: "https://github.com/igorshubovych/markdownlint-cli"
   rev: "v0.39.0"
   hooks:
    - id: markdownlint
      exclude: |
       (?x)^(
         issue_template\.md
       )
 - repo: "https://github.com/adrienverge/yamllint"
   rev: "v1.34.0"
   hooks:
    - id: yamllint
