---
repos:
 - repo: https://github.com/sphinx-contrib/sphinx-lint
   rev: "v1.0.2"
   hooks:
    - id: sphinx-lint
 - repo: https://github.com/PyCQA/doc8
   rev: v2.0.0
   hooks:
    - id: doc8
      files: ^docs/.*\.rst$
 - repo: "https://github.com/igorshubovych/markdownlint-cli"
   rev: "v0.46.0"
   hooks:
    - id: markdownlint
      exclude: |
       (?x)^(
         issue_template\.md
       )
 - repo: "https://github.com/adrienverge/yamllint"
   rev: "v1.37.1"
   hooks:
    - id: yamllint
      args: ["-d relaxed"]
